[project]
name = "myblog"
version = "0.1.0"
description = "Project that allow to post it on your blog blogger from org files."
authors = [
    {name = "Daniel Muñoz",email = "demunoz2@uc.cl"}
]
readme = "README.org"
requires-python = ">=3.11"
dependencies = [
    "orgparse (>=0.4.20250520,<0.5.0)",
    "google-api-python-client (>=2.185.0,<3.0.0)",
    "google-auth-oauthlib (>=1.2.2,<2.0.0)",
    "packaging (>=25.0,<26.0)"
]


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
publish-blog = "myblog.main:main"
