#+AUTHOR: Daniel Muñoz
#+TITLE: myBlog README

~MyBlog~ allows to create blog post as org files and then publish it on ~blogger~ executing a small script in ~python~. The title, and the tags are managed automatically by the script through the project metadata. The script is language-agnostic: it works with any post regardless of the language you write in (English, Spanish, etc.), since the content is exported to HTML by Emacs without further processing.

* Requirements
+ Python >=3.11
+ uv (https://docs.astral.sh/uv/getting-started/)
+ Emacs (optional, for editing org files)

* Installation

** Install uv
#+begin_src shell
curl -LsSf https://astral.sh/uv/install.sh | sh
#+end_src

** Clone and setup the project
#+begin_src shell
git clone https://github.com/koprotk/myBlog.git
cd myBlog
uv venv
source .venv/bin/activate  # On Windows: .venv\Scripts\activate
uv sync
#+end_src

* How to use it
1. Write your post on an org file in the ~drafts~ folder.
2. Put your Google credential file (a ~json~ file provided by Google) in the ~config~ folder (create it if it doesn't exist). The file is usually named ~client_secret_<id>.apps.googleusercontent.com.json~; any ~client_secret*.json~ name is accepted.
3. When you're ready to publish, run:

#+begin_src shell
publish-blog myDraftOrgfile.org
#+end_src

That's it! Your post will be published to Blogger.

* Tips and tricks
** Front image
If you want a front image for your post, link it as an image (must have an image extension) in this format: ~[[image url]]~ (without spaces). If you have a web link to an image that doesn't work directly, you can use a shortened URL or host it externally.

** Tags
The script extracts tags from your org file using ~#+TAGS: tag1 tag2 tag3~. If you don't use tags in your org file, the script will use the project name as a default tag.

** Development
To run the project in editable mode (for development):
#+begin_src shell
uv sync
source .venv/bin/activate
publish-blog myorgfile.org
#+end_src

To deactivate the virtual environment:
#+begin_src shell
deactivate
#+end_src
