#+AUTHOR: Daniel Muñoz
#+TITLE: myBlog README

~MyBlog~ allows to create blog post as org files and then publish it on ~blogger~ executing a small script in ~python~. The title, and the tags are managed automatically by the script through the package ~orgparse~ (requirement). The export from ~Org~ to ~HTML~ is made by Emacs itself (C-c C-e). All the process is completely unpainful and even you not need to touch your browser to publish your post, cool eh!?.

* Requirements
+ Python
+ Poetry
+ Emacs
  
* How to use it
1. Write your post on a org file on the ~draft~ folder.
2. Put your google credential file (a ~json~ file that google provide it) on the ~config~ folder (you need to create it) name it as ~client_secret.json~.
3. When you are sure to the post is ready to be publish run it.
4. How to run it? On a terminal run:
#+begin_src shell
poetry run publish-blog myorgfile.org
#+end_src

And that's it.

* Tips and tricks
** Front image
If you wanna a front image on your post, you can link it as image (should need image extension) in this form: ~[ [ image url ] ]~ (without spaces) but if you have a web link to the image that doesn't have image extension on the url you need to put it as HTML tag.
** Tags
The script takes the tags from your org file on ~#+TAGS: tag1 tag2 tag3~ use it. Are many positive arguments to use it, but here is the good one: *if don't use tags on your org file the script could fail.*
