#+AUTHOR: Daniel Muñoz
#+TITLE: myBlog README

~MyBlog~ allows to create blog post as org files and then publish it on ~blogger~ executing a small script in ~python~. The title, and the tags are managed automatically by the script through the package ~orgparse~ (requirement). The export from ~Org~ to ~HTML~ is made by Emacs itself (C-c C-e). All the process is completely unpainful and even you not need to touch your browser to publish your post, cool eh!?.

* First
Write your post on a org file on the ~draft~ folder:

* Second 
Put your google credentials (a ~json~ file that google provide it) on the ~config~ folder

* Third
When you are sure to the post is ready to be publish run it.

How to run it? On a terminal run:

#+begin_src shell
poetry run publish-blog myorgfile.org
#+end_src

And that's it.

* PS
If you wanna a front image on your post, you can link it as image (should need image extension) if you have a web link to the image that doesn't have image extension on the url you need to put it as HTML tag.
